Create SEQUENCE FIDE_ESTADO_SEQ
START WITH 1
INCREMENT BY 1;

Create SEQUENCE FIDE_PAIS_SEQ
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE FIDE_PROVINCIA_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_CANTON_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_DISTRITO_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_DIRECCION_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_NACIONALIDAD_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_ROLES_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_USUARIOS_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_ESTADOS_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_HOTELES_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_HABITACIONES_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_MANTENIMIENTO_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_TIPO_MANTENIMIENTO_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_LIMPIEZA_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_MONEDA_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_TIPO_CAMBIO_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_CATEGORIA_RESERVAS_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_RESERVAS_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_VALORACION_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_PROMOCIONES_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_TIPO_PROMOCION_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_IMPUESTOS_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_FACTURAS_SEQ 
START WITH 1 
INCREMENT BY 1;

CREATE SEQUENCE FIDE_DETALLE_FACTURA_SEQ 
START WITH 1 
INCREMENT BY 1;
///////////////////////////////////////////////////////
CREATE OR REPLACE TRIGGER FIDE_ESTADO_ID_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
:NEW.id_estado:=FIDE_ESTADO_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_PAIS_ID_TRG
BEFORE INSERT ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
:NEW.id_pais:=FIDE_PAIS_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_PROVINCIA_ID_TRG
BEFORE INSERT ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
    :NEW.id_provincia := FIDE_PROVINCIA_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_CANTON_ID_TRG
BEFORE INSERT ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
    :NEW.id_canton := FIDE_CANTON_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_DISTRITO_ID_TRG
BEFORE INSERT ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
    :NEW.id_distrito := FIDE_DISTRITO_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_DIRECCION_ID_TRG
BEFORE INSERT ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
    :NEW.id_direccion := FIDE_DIRECCION_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_NACIONALIDAD_ID_TRG
BEFORE INSERT ON FIDE_NACIONALIDAD_TB
FOR EACH ROW
BEGIN
    :NEW.ID_Nacionalidad := FIDE_NACIONALIDAD_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_ROLES_ID_TRG
BEFORE INSERT ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
    :NEW.id_rol := FIDE_ROLES_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_USUARIOS_ID_TRG
BEFORE INSERT ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_usuario := FIDE_USUARIOS_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_ESTADOS_ID_TRG
BEFORE INSERT ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_estado := FIDE_ESTADOS_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_HOTELES_ID_TRG
BEFORE INSERT ON FIDE_HOTELES_TB
FOR EACH ROW
BEGIN
    :NEW.id_hotel := FIDE_HOTELES_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_HABITACIONES_ID_TRG
BEFORE INSERT ON FIDE_HABITACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.id_habitacion := FIDE_HABITACIONES_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_MANTENIMIENTO_ID_TRG
BEFORE INSERT ON FIDE_MANTENIMIENTO_TB
FOR EACH ROW
BEGIN
    :NEW.id_mantenimiento := FIDE_MANTENIMIENTO_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_TIPO_MANT_ID_TRG
BEFORE INSERT ON FIDE_TIPO_MANTENIMIENTO_TB
FOR EACH ROW
BEGIN
    :NEW.id_tipo_mantenimiento := FIDE_TIPO_MANTENIMIENTO_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_LIMPIEZA_ID_TRG
BEFORE INSERT ON FIDE_LIMPIEZA_HABITACIONES_TB
FOR EACH ROW
BEGIN
    :NEW.id_limpieza := FIDE_LIMPIEZA_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_MONEDA_ID_TRG
BEFORE INSERT ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
    :NEW.id_moneda := FIDE_MONEDA_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_TIPO_CAMBIO_ID_TRG
BEFORE INSERT ON FIDE_TIPO_CAMBIO_TB
FOR EACH ROW
BEGIN
    :NEW.id_tipo_cambio := FIDE_TIPO_CAMBIO_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_CAT_RESERVAS_ID_TRG
BEFORE INSERT ON FIDE_CATEGORIA_RESERVAS_TB
FOR EACH ROW
BEGIN
    :NEW.id_categoria := FIDE_CATEGORIA_RESERVAS_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_RESERVAS_ID_TRG
BEFORE INSERT ON FIDE_RESERVAS_TB
FOR EACH ROW
BEGIN
    :NEW.id_reservacion := FIDE_RESERVAS_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_VALORACION_ID_TRG
BEFORE INSERT ON FIDE_VALORACION_TB
FOR EACH ROW
BEGIN
    :NEW.id_valoracion := FIDE_VALORACION_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_PROMOCIONES_ID_TRG
BEFORE INSERT ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
    :NEW.id_promocion := FIDE_PROMOCIONES_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_TIPO_PROMO_ID_TRG
BEFORE INSERT ON FIDE_TIPO_PROMOCION_TB
FOR EACH ROW
BEGIN
    :NEW.id_tipo_promocion := FIDE_TIPO_PROMOCION_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_IMPUESTOS_ID_TRG
BEFORE INSERT ON FIDE_IMPUESTOS_TB
FOR EACH ROW
BEGIN
    :NEW.id_impuesto := FIDE_IMPUESTOS_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_FACTURAS_ID_TRG
BEFORE INSERT ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
    :NEW.id_factura := FIDE_FACTURAS_SEQ.NEXTVAL;
END;

/

CREATE OR REPLACE TRIGGER FIDE_DET_FACTURA_ID_TRG
BEFORE INSERT ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
    :NEW.id_detalle_factura := FIDE_DETALLE_FACTURA_SEQ.NEXTVAL;
END;






