Create or Replace trigger FIDE_ESTADOS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_ESTADOS_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_ESTADOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ESTADOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_PAIS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_PAIS_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_PAIS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PAIS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_PROVINCIA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_PROVINCIA_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_PROVINCIA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROVINCIA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_CANTON_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_CANTON_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_CANTON_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CANTON_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_DISTRITO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_DISTRITO_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_DISTRITO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DISTRITO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_DIRECCION_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_DIRECCION_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_DIRECCION_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DIRECCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_NACIONALIDAD_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_NACIONALIDAD_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_NACIONALIDAD_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_NACIONALIDAD_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_NACIONALIDAD_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_NACIONALIDAD_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_ROLES_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_ROLES_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_ROLES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_ROLES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_MONEDA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_MONEDA_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_MONEDA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_MONEDA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_TIPO_MANTENIMIENTO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_MANTENIMIENTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_TIPO_MANTENIMIENTO_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_MANTENIMIENTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_TIPO_MANTENIMIENTO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_MANTENIMIENTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_TIPO_PROMOCION_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_PROMOCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_TIPO_PROMOCION_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_PROMOCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_TIPO_PROMOCION_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_PROMOCION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_USUARIOS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_USUARIOS_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_USUARIOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_USUARIOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_HOTELES_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_HOTELES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_HOTELES_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_HOTELES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_HOTELES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_HOTELES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_HABITACIONES_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_HABITACIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_HABITACIONES_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_HABITACIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_HABITACIONES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_HABITACIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_VALORACION_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_VALORACION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_VALORACION_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_VALORACION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_VALORACION_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_VALORACION_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_CATEGORIA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_RESERVAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_CATEGORIA_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_RESERVAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_CATEGORIA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_CATEGORIA_RESERVAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_RESERVAS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_RESERVAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_RESERVAS_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_RESERVAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_RESERVAS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_RESERVAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_PROMOCIONES_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_PROMOCIONES_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_PROMOCIONES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_PROMOCIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_IMPUESTOS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_IMPUESTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_IMPUESTOS_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_IMPUESTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_IMPUESTOS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_IMPUESTOS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_FACTURAS_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_FACTURAS_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_FACTURAS_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_FACTURAS_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_DETALLE_FACTURA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_DETALLE_FACTURA_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_DETALLE_FACTURA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_DETALLE_FACTURA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_RESERVAS_FACTURA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_RESERVAS_FACTURA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_RESERVAS_FACTURA_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_RESERVAS_FACTURA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_RESERVAS_FACTURA_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_RESERVAS_FACTURA_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_TIPO_CAMBIO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_CAMBIO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_TIPO_CAMBIO_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_CAMBIO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_TIPO_CAMBIO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_TIPO_CAMBIO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_MANTENIMIENTO_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_MANTENIMIENTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_MANTENIMIENTO_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_MANTENIMIENTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_MANTENIMIENTO_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_MANTENIMIENTO_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;

/

Create or Replace trigger FIDE_LIMPIEZA_HABITACIONES_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_LIMPIEZA_HABITACIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.CREADO_POR:=USER;
ELSE
:NEW.MODIFICADO_POR:=USER;
END IF;
END;

/

Create or Replace trigger FIDE_LIMPIEZA_HABITACIONES_FECHA_CREADO_MODIFICADO_POR_TRG
BEFORE INSERT OR UPDATE ON FIDE_LIMPIEZA_HABITACIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.FECHA_CREACION:=SYSTIMESTAMP;
ELSE
:NEW.FECHA_MODIFICACION:=SYSTIMESTAMP;
END IF;
END;

/

Create or Replace TRIGGER FIDE_LIMPIEZA_HABITACIONES_ACCION_TRG
BEFORE INSERT OR UPDATE ON FIDE_LIMPIEZA_HABITACIONES_TB
FOR EACH ROW
BEGIN
IF INSERTING THEN
:NEW.ACCION:='INSERT';
ELSIF UPDATING THEN
:NEW.ACCION:='UPDATE';
END IF;
END;


